Feature/auth
Sinnabro/Sinnabro-Frontend pull request #5
Opened 2022-11-13 08:38 UTC by SEOg-u

2022-11-13 12:42 UTC, applely25 requested changes

2022-11-13 12:42 UTC, applely25 commented on src/components/Header.js
> +import { useEffect, useState } from "react";
왜 헤더 코드가 있어요??

2022-11-13 23:32 UTC, SEOg-u commented on src/components/Header.js
> +import { useEffect, useState } from "react";
실수네요. 죄송합니다.

2022-11-14 05:36 UTC, applely25 commented on src/components/Header.js
> +import { useEffect, useState } from "react";
헤더코드 없애고 머지해주세요

2022-11-17 23:56 UTC, applely25 approved these changes

2022-11-17 23:57 UTC, merged